## YAML Template.
---
language: php
branches:
  only:
    - master
php:
  - 5.4

before_script:
  - composer install
script: phpunit --configuration ./tests/StopInjectionTest/travis_configuration.xml
